fix: Add OLM channel for minor versions
redhat-openshift-builds/catalog pull request #13
Opened 2024-08-26 14:18 UTC by sayan-biswas

Changes:
- Add OLM channel for minor versions, `openshift-builds-1.0` and `openshift-builds-1.1`

2024-08-26 15:55 UTC, adambkaplan commented
Asking that we hold this pull request until #14 merges (and this PR is then rebased).

2024-08-27 19:24 UTC, sayan-biswas commented
@adambkaplan Can this PR be merged? All the previous channels are also restored in this.

2024-08-29 14:47 UTC, adambkaplan requested changes
Name change for the v1.1 channel (suggestion needs to be copied to the other OCP versions).

Otherwise looks good - I'll close my competing PR.

2024-08-29 14:47 UTC, adambkaplan commented on catalog/v4.12/openshift-builds-operator/catalog.yaml
> +name: stable-v1
:+1: to restoring stable-v1. This PR should replace mine (#14)

2024-08-29 14:47 UTC, adambkaplan commented on catalog/v4.12/openshift-builds-operator/catalog.yaml
> +name: openshift-builds-1.1
Per discussion in Slack, rename this to `builds-1.1`

```suggestion
name: builds-1.1
```

@sayan-biswas We need to add a release note that we are changing the channel naming convention to "builds-1.N" for z-stream only updates.

2024-08-29 15:29 UTC, sayan-biswas commented on catalog/v4.12/openshift-builds-operator/catalog.yaml
> +name: openshift-builds-1.1
updated!

2024-08-29 18:45 UTC, merged